# LAB 1: Matrix and Vector Computations in python

In this lab you will use python to study the following topics:

- How to create matrices and vectors in python.

- How to manipulate matrices in python and create matrices of special types.

- How to add matrices and multiply a vector by a matrix by python.

- Apply linear transformation.


# First: you should run this cell

In [13]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

import matplotlib.pyplot as plt

# Question 1 :Declaring scalars, vectors, and matrices

a) Use [numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) to declare the following:

1. A scalar $s = 5$
2. A vector $v = \begin{bmatrix} 5  \\ -2 \\ 4  \\ \end{bmatrix}$
3. A matrix $A = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ 7 & 8 & 9  \\ \end{bmatrix}$
4. A matrix $B = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ \end{bmatrix}$
5. A matrix $C = \begin{bmatrix} 1 & 2   \\ 3 & 4  \\ 5 & 6   \\ \end{bmatrix}$

In [2]:
#type your code here:


s = 5

v =
 [[ 5]
 [-2]
 [ 4]]

A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

B =
 [[1 2 3]
 [4 5 6]]

C =
 [[1 2]
 [3 4]
 [5 6]]



In [18]:
s = np.array(5)
v = np.array([[ 5],
 [-2],
 [ 4]])
    
A = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

B = np.array([[1, 2, 3],
 [4, 5, 6]])

C = np.array([[1, 2],
 [3, 4],
 [5, 6]])
print(s)
print(v)
print(A)

5
[[ 5]
 [-2]
 [ 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


b) Print the data type of $s, v,$ and $A$ using `type` command in python.

In [3]:
#type your code here:


type(s) = <class 'numpy.ndarray'>

type(v) = <class 'numpy.ndarray'>

type(A) = <class 'numpy.ndarray'>



In [19]:
print(type(s))
print(type(v))
print(type(A))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


c) Using [numpy.shape](https://numpy.org/devdocs/reference/generated/numpy.shape.html) or `A.shape` print the shape of $s, v, A, B,$ and $C$.

In [4]:
#type your code here:


s.shape = ()

v.shape = (3, 1)

A.shape = (3, 3)

B.shape = (2, 3)

C.shape = (3, 2)



In [20]:
print(s.shape)
print(v.shape)
print(A.shape)
print(B.shape)
print(C.shape)

()
(3, 1)
(3, 3)
(2, 3)
(3, 2)


d) To access a given entry in the `numpy array` put the `row number - 1` and `column number - 1` in square brackets following the array name. Ex `a32 = A[2, 1]`.
- Print the value of the third row and the second column of the matrix $A$.
- Change it to $10$.
- Print the matrix A to check the entry is changed.

In [5]:
#type your code here:


A[2, 1] =  8

A =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]



In [22]:
print(A[2, 1])
A[2, 1] =  10
print(A[2, 1])

8
10


e)To access a whole row or column of a matrix, use the colon operator. For example, `A[:, [1]]` is the second column of A, while `B[[1], :]` is the second row of B.

In [23]:
#type your code here:
print(A[:, [1]])
print(B[[1], :])

[[ 2]
 [ 5]
 [10]]
[[4 5 6]]


f) Type each of the following commands that generate special matrices:
- `np.eye(4), np.zeros(3), np.zeros((3, 1)), np.zeros((3, 5)), np.ones((2, 3)), and np.diag([4, 5, 6, 7])`

In [2]:
#type your code here:


np.eye(4) =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

np.zeros(3) =
 [0. 0. 0.]

np.zeros((3, 1)) =
 [[0.]
 [0.]
 [0.]]

np.zeros((3, 5)) =
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

np.ones((2, 3)) =
 [[1. 1. 1.]
 [1. 1. 1.]]

np.diag([4 5 6 7]) =
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


In [26]:
print(np.eye(4))
print(np.zeros(3))
print(np.zeros((3, 1)))
print(np.zeros((3, 5)))
print(np.ones((2, 3)))
print(np.diag([4, 5, 6, 7]))

# np.eye(4), np.zeros(3), np.zeros((3, 1)), np.zeros((3, 5)), np.ones((2, 3)), and np.diag([4, 5, 6, 7])

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0. 0. 0.]
[[0.]
 [0.]
 [0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


# Question 2. Vectors Addition, Scaling, and dot product

a) Declare vectors $v1 = \begin{bmatrix} 1  \\ 2 \\ 7  \\ 4 \\ \end{bmatrix}$ and $v2 = \begin{bmatrix} 4  \\ 3 \\ 6  \\ 8 \\ \end{bmatrix}$

- Addition: $v1 + v2$
- Subtraction: $v1 - v2$
- Scaling by a number: $3 * v1$
- Scaling by a number: $v1 / 2$

In [8]:
#type your code here:


v1 =
 [[1]
 [2]
 [7]
 [4]]

v2 =
 [[4]
 [3]
 [6]
 [8]]

v1 + v2 =
 [[ 5]
 [ 5]
 [13]
 [12]]

v1 - v2 =
 [[-3]
 [-1]
 [ 1]
 [-4]]

3*v1 =
 [[ 3]
 [ 6]
 [21]
 [12]]

v1/2 =
 [[0.5]
 [1. ]
 [3.5]
 [2. ]]



In [28]:
v1 =np.array([[1],
 [2],
 [7],
 [4]])

v2 =np.array([[4],
 [3],
 [6],
 [8]])
print(v1)
print(v2)
print(v1 + v2)
print(v1 - v2)
print(3*v1)
print(v1/2)

[[1]
 [2]
 [7]
 [4]]
[[4]
 [3]
 [6]
 [8]]
[[ 5]
 [ 5]
 [13]
 [12]]
[[-3]
 [-1]
 [ 1]
 [-4]]
[[ 3]
 [ 6]
 [21]
 [12]]
[[0.5]
 [1. ]
 [3.5]
 [2. ]]


b) Find the dot product between the two vectors $v1$ and $v2$ using the following:

- [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)
- `v1.T @ v2`

In [9]:
#type your code here:
np.dot(v1.T, v2)

Using numpy.dot =
 [[84]]

Using numpy.matmul =
 [[84]]

Using @ =
 [[84]]



In [29]:
print(np.dot(v1.T, v2))
print(np.matmul(v1.T, v2))

[[84]]
[[84]]


c) Find the length of the vectors $v1$ and $v2$.
- Using [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)
- Using the dot product and [numpy.sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)


In [10]:
#type your code here:


length of v1 Using numpy.linalg.norm =
 8.366600265340756

length of v2 Using numpy.linalg.norm =
 11.180339887498949

length of v1 Using the dot product and numpy.sqrt =
 [[8.36660027]]

length of v2 Using the dot product and numpy.sqrt =
 [[11.18033989]]



In [37]:
print(np.linalg.norm(v1))
print(np.linalg.norm(v2))
print(np.sqrt(np.dot(v1.T,v1)))
print(np.sqrt(np.dot(v2.T,v2)))

8.366600265340756
11.180339887498949
[[8.36660027]]
[[11.18033989]]


d) Show that the vectors $u = \begin{bmatrix} 3  \\ 2 \\ -1  \\ 4 \\ \end{bmatrix}$ and $v = \begin{bmatrix} 1  \\ -1 \\ 1  \\ 0 \\ \end{bmatrix}$ are orthogonal.


In [11]:
#type your code here:


u.T @ v =
 [[0]]



In [38]:
u = np.array([[3],
 [2],
 [-1],
 [4]])
v = np.array([[1],
 [-1],
 [1],
 [0]])
np.dot(u.T,v)

array([[0]])

# Question 3. Matrix Addition and Matrix-Vector Multiplication

Declare vectors $u$ and $v$ and matrices $A$ and $B$ as following:
- $u = \begin{bmatrix} 2  \\ 7 \\ 2 \\ \end{bmatrix}$, $v = \begin{bmatrix} 8  \\ 2 \\ 4 \\ \end{bmatrix}$
- $A = \begin{bmatrix} 7 & 3 & 5  \\ 4 & 6 & 2 \\ \end{bmatrix}$, $B = \begin{bmatrix} 0 & 6 & 4  \\ 2 & 3 & 0 \\ \end{bmatrix}$

a) Calculate the following using python.

- $A+B$
- $B+A$
- $3A$
- $6B$
- $2(3B)$
- $6A+15B$
- $3(2A+5B)$

In [42]:
u = np.array([[2],
 [7],
 [2]])
v = np.array([[8],
 [2],
 [4]])
A = np.array([[7, 3, 5],
 [4, 6, 2]])
B = np.array([[0, 6, 4],
 [2, 3, 0]])
print(A + B)
print(B + A)
print(3*A)
print(6*B)
print(2*(3*B))
print(6*A + 15*B)
print(3*(2*A + 5*B))

[[7 9 9]
 [6 9 2]]
[[7 9 9]
 [6 9 2]]
[[21  9 15]
 [12 18  6]]
[[ 0 36 24]
 [12 18  0]]
[[ 0 36 24]
 [12 18  0]]
[[ 42 108  90]
 [ 54  81  12]]
[[ 42 108  90]
 [ 54  81  12]]


In [12]:
#type your code here:


u =
 [[2]
 [7]
 [2]]

v =
 [[8]
 [2]
 [4]]

A =
 [[7 3 5]
 [4 6 2]]

B =
 [[0 6 4]
 [2 3 0]]

A + B =
 [[7 9 9]
 [6 9 2]]

B + A =
 [[7 9 9]
 [6 9 2]]

3A =
 [[21  9 15]
 [12 18  6]]

6B =
 [[ 0 36 24]
 [12 18  0]]

2(3B) =
 [[ 0 36 24]
 [12 18  0]]

6A + 15B =
 [[ 42 108  90]
 [ 54  81  12]]

3(2A + 5B) =
 [[ 42 108  90]
 [ 54  81  12]]



b) To obtain the matrix-vector product $Au$ using python, type `A @ u`. Calculate the following:

- $Au+Av$
- $A(u+v)$
- $(A+B)u$
- $Au+Bu$
- $A(3u)$
- $3A(u)$

In [45]:
print(np.dot(A,u) + np.dot(A,v))

[[127]
 [106]]


In [13]:
#type your code here:


Au + Av =
 [[127]
 [106]]

A(u + v) =
 [[127]
 [106]]

(A + B)u =
 [[95]
 [79]]

Au + Bu =
 [[95]
 [79]]

A(3u) =
 [[135]
 [162]]

3A(u) =
 [[135]
 [162]]



# Question 4: Linear Transformation

Declare a vector $v = \begin{bmatrix} 5  \\ -2 \\ \end{bmatrix}$

a) Rotations: Generate a matrix Q and Let Q act on the vector

$Q = \begin{bmatrix} cos(\theta) & -sin(\theta)   \\ sin(\theta) & cos(\theta)    \\ \end{bmatrix}$ where $\theta = pi / 6$

- Repeat with $\theta = -pi/3$
- Use [matplotlib.pyplot.quiver](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.quiver.html) to plot the vectors. Ex: `plt.quiver(v1[0], v1[1], angles='xy', scale_units='xy', scale=1, color='red', alpha=1)`
- Describe in words how the vector has changed.


In [ ]:
#type your code here:


In [48]:
v = np.array([[5],[-2]])
#Q = np.array([[np.cos(30),np.sin(30)],[-np.sin(30),np.cos(30)]])
Q = np.array([np.cos(30),np.sin(30),-np.sin(30),np.cos(30)]).reshape(2,2)
print(Q@v)

[[2.7473205 ]
 [4.63165522]]


b) Dilations: Generate a matrix D by

$D = \begin{bmatrix} r & 0   \\ 0 & 1/r    \\ \end{bmatrix}$ where $r = 0.9$

- Repeat with $r = 0.8$
- Use [matplotlib.pyplot.quiver](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.quiver.html) to plot the vectors
- Describe in words how the vector has changed.

In [ ]:
#type your code here:


In [49]:
r = 0.9
D = np.array([r,0,0,(1/r)]).reshape(2,2)
print(D)
r = 0.8
D = np.array([r,0,0,(1/r)]).reshape(2,2)
print(D)

[[0.9        0.        ]
 [0.         1.11111111]]
[[0.8  0.  ]
 [0.   1.25]]


c) Shearing Transformations: Generate a matrix T by
$T = \begin{bmatrix} 1 & t   \\ 0 & 1    \\ \end{bmatrix}$ where $t = 0.5$

- Repeat with $t = -0.5$
- Use [matplotlib.pyplot.quiver](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.quiver.html) to plot the vectors
- Describe in words how the vector has changed.

In [ ]:
#type your code here:


In [50]:
t = 0.5
T = np.array([1,t,0,1]).reshape(2,2)
print(T)
t = -0.5
T = np.array([1,t,0,1]).reshape(2,2)
print(T)


[[1.  0.5]
 [0.  1. ]]
[[ 1.  -0.5]
 [ 0.   1. ]]


In [ ]:
https://github.com/Ibn-mohey/ITI.Path/blob/main/linear%20algebra/LA_ITI_PRO_Student_Lab_1.ipynb