# Session 3 - Solving System of Linear Equations

In [2]:
import numpy as np

A = np.array([
    [10., -1., 2., 0.],
    [-1., 11., -1., 3.],
    [2., -1., 10., -1.],
    [0., 3., -1., 8.]
])

b = np.array([6., 25., -11., 15.])

## Jacobi's Method

$$ x^{(k)} = D^{-1}b - D^{-1} (L+U)x^{(k-1)}$$
$$ x^{(k)} = D^{-1}(b - (L+U)x^{(k-1)}) $$

Stop criteria = $||x^{(k)} - x^{(k-1)} || / ||x^{(k)}|| < tolerance$

In [52]:
from numpy.linalg import inv, solve, norm

def jacobi(A, b, tolerance):
    xk_1 = np.zeros_like(b)
    D = np.diag(A)
#     print(D)
    LplusU = A - np.diag(D)
#     print(LplusU)
#     print((b - LplusU @ xk_1) / D)
#     print(np.diag(D) @ (b - (LplusU @ xk_1))
    
    x_k = (b - (LplusU @ xk_1)) / D
    while (norm(x_k - xk_1, 2)/norm(x_k, 2)) > tolerance:
        xk_1 = x_k
        x_k = (b - (LplusU @ xk_1)) / D
    
#     for i in range(N):
#         x = (b - LplusU.dot(x)) / D
    return x_k

print(jacobi(A, b, 1e-8))


[3.9645e+153 4.8409e+153 4.0729e+153 8.1327e+153 7.8089e+153]


C:\Users\osama\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in double_scalars
  del sys.path[0]


## Gauss-Siedel Method

In [47]:
from numpy.linalg import inv

def siedel(A, b, N):
    x = np.zeros_like(b) # initial solution (zeros)
    LD = np.tril(A)
    U = A - LD
#     print(LD)
#     print(U)
    LDinv = inv(LD)
    for i in range(N):
        x = LDinv @ (b - U@x)
    return x
    
    

siedel(A, b, 9)

array([ 1.,  2., -1.,  1.])

## Diagonally Dominant Matrices

In [64]:
np.set_printoptions(precision=4)
N = 10
for f in range(1, 50):
#     f = 0.01
    A = np.eye(N) * f
    A += np.random.rand(N, N)
    b = A @ np.ones(N)

    x = jacobi(A, b, 1e-6)
    print(x)



C:\Users\osama\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in double_scalars
  del sys.path[0]


[9.3170e+153 7.8562e+153 5.6941e+153 6.2659e+153 6.9283e+153 4.7585e+153
 7.2820e+153 9.5474e+153 9.6081e+153 4.7835e+153]
[-3.2298e+153 -5.9729e+153 -3.6157e+153 -5.3852e+153 -5.0202e+153
 -4.3026e+153 -5.5848e+153 -3.9914e+153 -5.9283e+153 -3.7954e+153]
[-5.8067e+153 -4.6916e+153 -6.1585e+153 -6.4089e+153 -3.8484e+153
 -4.7922e+153 -4.3801e+153 -4.5381e+153 -4.8894e+153 -5.4398e+153]
[3.9710e+153 4.7104e+153 3.3456e+153 3.2654e+153 5.1339e+153 2.6460e+153
 4.2265e+153 4.4132e+153 4.0761e+153 5.7195e+153]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1

## The Power Method

In [82]:
from numpy.linalg import eig

A = np.array([
    [10., -1., 2., 0.],
    [-1., 11., -1., 3.],
    [2., -1., 10., -1.],
    [0., 3., -1., 8.]
])

l, v = eig(A)
print(l)
print(v)

print()

print(A @ v[:, 0])
print(l[0] * v[:, 0])

x = np.random.rand(4)
for i in range(50):
    x = (A @ x) / norm(x,2)

lmbda = ((A@x) / x)[0]
v = x / lmbda
print(lmbda)
print(v)

[14.0735 10.8191  8.1434  5.964 ]
[[ 0.3935 -0.6234 -0.6404 -0.2155]
 [-0.6802 -0.4913  0.2267 -0.4945]
 [ 0.4613 -0.5009  0.7079  0.1877]
 [-0.4119 -0.3451 -0.1934  0.8208]]

[ 5.5376 -9.5729  6.4921 -5.7975]
[ 5.5376 -9.5729  6.4921 -5.7975]
14.073435652863134
[ 0.028  -0.0483  0.0328 -0.0293]


## The PageRank Algorithm